services:
  db:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: my-resume-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres-dev
      - NODE_ENV
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - CHOKIDAR_USEPOLLING
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_module/
        - action: rebuild
          path: package.json

volumes:
  postgres_data:
